tap 'homebrew/bundle'

brew 'awscli'
brew 'ghq'
brew 'git'
brew 'go'
brew 'peco'
brew 'tmux'
brew 'tree'
brew 'neovim'
brew 'zsh'
brew 'mas'
brew 'fish'
brew 'exa'
brew 'bat'
brew 'hexyl'
brew 'fd'
brew 'procs'
brew 'ripgrep'
brew 'lazygit'
brew 'reattach-to-user-namespace'

cask 'google-chrome'
cask 'gyazo'
cask '1password'
cask 'alfred'
cask 'appcleaner'
cask 'shiftit'
cask 'clipy'
cask 'dash'
cask 'docker'
cask 'karabiner-elements'
cask 'keycast'

mas "Slack", id:803453959
mas "Kindle", id:405399194
mas "Yoink", id:457622435
mas "BetterSnapTool", id:417375580
# vim: ft=conf
